version: "3"

services:
  eureka:
    container_name: eureka
    image: d4ramirez/discovery:latest
    environment:
      - SERVER_PORT=8671
    ports:
      - 8761:8761

  calculator:
    container_name: calculator
    image: d4ramirez/calculator:latest
    environment:
      - SERVER_PORT=8888
    ports:
      - 8888:8888

  add:
    container_name: add
    image: d4ramirez/add:latest
    environment:
      - SERVER_PORT=1010
    ports:
      - 1010:1010
  
  substract:
    container_name: substract
    image: d4ramirez/substract:latest
    environment:
      - SERVER_PORT=2020
    ports:
      - 2020:2020
  
  multiply:
    container_name: multiply
    image: d4ramirez/multiply:latest
    environment:
      - SERVER_PORT=3030
    ports:
      - 3030:3030
  
  divide:
    container_name: divide
    image: d4ramirez/divide:latest
    environment:
      - SERVER_PORT=4040
    ports:
      - 4040:4040
