version: "3"

services:
  eureka:
    build:
      context: "./services/service-discovery"
      dockerfile: "../../common/Dockerfile"
    environment:
      - SERVER_PORT=8761
    ports:
      - 8761:8761

  calculator:
    build:
      context: "./services/calculator"
      dockerfile: "../../common/Dockerfile"
    environment:
      - SERVER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - eureka

  add:
    build:
      context: "./services/add"
      dockerfile: "../../common/Dockerfile"
    environment:
      - SERVER_PORT=1010
    ports:
      - "1010"
    depends_on:
      - eureka
      - calculator
  
  substract:
    build:
      context: "./services/substract"
      dockerfile: "../../common/Dockerfile"
    environment:
      - SERVER_PORT=2020
    ports:
      - "2020"
    depends_on:
      - eureka
      - calculator
  
  multiply:
    build:
      context: "./services/multiply"
      dockerfile: "../../common/Dockerfile"
    environment:
      - SERVER_PORT=3030
    ports:
      - "3030"
    depends_on:
      - eureka
      - calculator
  
  divide:
    build:
      context: "./services/divide"
      dockerfile: "../../common/Dockerfile"
    environment:
      - SERVER_PORT=4040
    ports:
      - "4040"
    depends_on:
      - eureka
      - calculator
